Adding k8s 1.11 support to readme
cyberark/secrets-provider-for-k8s pull request #279
Opened 2020-12-24 07:11 UTC by Tovli

### What does this PR do?
- _What's changed? Why were these changes made?_
 Added k8s 1.11 support and updated list of maintainers
- _How should the reviewer approach this PR, especially if manual tests are required?_
- _Are there relevant screenshots you can add to the PR description?_

### What ticket does this PR close?
Resolves #[relevant GitHub issues, eg 76]

### Checklists

#### Change log
- [ ] The CHANGELOG has been updated, or
- [x] This PR does not include user-facing changes and doesn't require a CHANGELOG update

#### Test coverage
- [ ] This PR includes new unit and integration tests to go with the code changes, or
- [x] The changes in this PR do not require tests

#### Documentation
- [x] Docs (e.g. `README`s) were updated in this PR, and/or there is a follow-on issue to update docs, or
- [ ] This PR does not require updating any documentation

2020-12-24 08:43 UTC, orenbm commented on README.md
> +- K8S 1.11+
nit: please change to `K8s` (small `s`)

2020-12-24 08:45 UTC, orenbm requested changes
left a small comment

2020-12-25 14:42 UTC, Tovli commented on README.md
> +- K8S 1.11+
Done
Please re-review

2020-12-27 08:11 UTC, orenbm approved these changes

2020-12-27 08:11 UTC, merged