Add support for newer openshift labels
cyberark/secrets-provider-for-k8s pull request #309
Opened 2021-03-09 20:31 UTC by BradleyBoutcher

### What does this PR do?
We now support running tests against the 'next', 'current', and 'oldest' versions of Openshift, as defined in Conjurops.

Currently, only 'current' and 'next' are supported

### What ticket does this PR close?
Resolves #302 

### Checklists

#### Change log
- [ ] The CHANGELOG has been updated, or
- [X] This PR does not include user-facing changes and doesn't require a CHANGELOG update

#### Test coverage
- [ ] This PR includes new unit and integration tests to go with the code changes, or
- [X] The changes in this PR do not require tests

#### Documentation
- [X] Docs (e.g. `README`s) were updated in this PR, and/or there is a follow-on issue to update docs, or
- [ ] This PR does not require updating any documentation

2021-03-10 17:45 UTC, orenbm commented on Jenkinsfile
> +                sh "./bin/start --docker --dap --current"
thanks @BradleyBoutcher for getting this!
Can we verify that the OCP version is logged in a clear place so we know which versions are tested in each Jenkins run?

2021-03-10 17:46 UTC, orenbm submitted a review, later dismissed
Thanks @BradleyBoutcher !

Just blocking this PR from being merged just so we don't merge the OSS tests removal by accident :)

2021-03-15 14:15 UTC, izgeri commented on Jenkinsfile
> -                  sh "./bin/start --docker --dap --oc311"
we will need to keep the 3.11 tests in here for now

2021-03-15 14:15 UTC, izgeri commented on Jenkinsfile
> +              tasks["Openshift (Current), DAP"] = {
maybe we should add a test flow against `oldest` but comment it out for now? oldest is currently 4.3, and SP is not certified for 4.3

2021-03-18 16:25 UTC, diverdane commented on bin/start
> +    --oldest     Run the integration tests on the oldest running Openshift platform. By default the tests are run on GKE.
Silly nit: The spacing before the word `Run` is off by 1 for `--oldest` and `--next` options.
That's all I've got, everything else looks good to me (beyond comments already made).

2021-03-19 15:41 UTC, izgeri requested changes
A few minor comments. Also, we should be adding a CHANGELOG entry about validing the secrets provider on OpenShift 4.6.

2021-03-19 15:41 UTC, izgeri commented on bin/start
> +    summon -p summon-conjur --environment $SUMMON_ENV -f ./summon/secrets.yml $1
nit, but if we add this here let's use the long form of the flag `--provider`

2021-03-19 15:41 UTC, izgeri commented on deploy/run_with_summon.sh
> +echo "Running tests on: ${PLATFORM} ${OPENSHIFT_VERSION}"
can we use `announce` instead of echo? it will def get lost in the logs with just echo.

2021-03-19 15:41 UTC, izgeri commented on deploy/summon/secrets.yml
> +  TEST_PLATFORM: !var ci/openshift/oldest/version
it looks like kubernetes-conjur-deploy expects this to be `openshift*` (though I'm not sure why it's working now)
https://github.com/cyberark/kubernetes-conjur-deploy/blob/fbe14df8a20e451ffdebca0d4b73c85df52d2bcc/test.sh#L43-L51

you can probably just make them all the literal strings `openshift` instead
```suggestion
  TEST_PLATFORM: openshift
```

2021-03-19 15:41 UTC, izgeri commented on deploy/summon/secrets.yml
> +  TEST_PLATFORM: !var ci/openshift/current/version
```suggestion
  TEST_PLATFORM: openshift
```

2021-03-19 15:41 UTC, izgeri commented on deploy/summon/secrets.yml
> +  TEST_PLATFORM: !var ci/openshift/next/version
```suggestion
  TEST_PLATFORM: openshift
```

2021-03-19 15:43 UTC, izgeri commented on deploy/summon/secrets.yml
> +  TEST_PLATFORM: !var ci/openshift/oldest/version
btw, this seems silly and redundant now. makes me think we should just change the logic in k8s-deploy to use `PLATFORM`, remove `TEST_PLATFORM` from that project, and then remove it from here.

2021-03-19 16:17 UTC, izgeri reviewed
LGTM, but if we can verify that `next` is passing we should update the [supported platforms](https://github.com/cyberark/secrets-provider-for-k8s/#supported-platforms) in the README with this PR to include 4.6

2021-03-19 16:25 UTC, izgeri approved these changes
LGTM pending green build, including with `next` pipeline

2021-03-19 21:35 UTC, izgeri commented
It's all green, including on OCP 4.6! See [Jenkins](https://jenkins.conjur.net/blue/organizations/jenkins/cyberark--secrets-provider-for-k8s/detail/add-openshift-envs/27/pipeline/) for confirmation. Thanks @BradleyBoutcher !!

2021-03-19 21:35 UTC, merged