Adding documentation for Secrets Rotation
cyberark/secrets-provider-for-k8s pull request #443
Opened 2022-02-24 20:17 UTC by rpothier

### Desired Outcome

There should be documentation for the Secrets Rotation feature.

### Implemented Changes

Added ROTATION.md, updated the other README.md and PUSH_TO_FILE.md
Also updated one of the error messges.

### Connected Issue/Story

Resolves #[relevant GitHub issue(s), e.g. 76]

CyberArk internal issue link: [ONYX-16906](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-16906)

### Definition of Done
*At least 1 todo must be completed in the sections below for the PR to be
merged.*

#### Changelog

- [ ] The CHANGELOG has been updated, or
- [X] This PR does not include user-facing changes and doesn't require a
  CHANGELOG update

#### Test coverage

- [ ] This PR includes new unit and integration tests to go with the code
  changes, or
- [X] The changes in this PR do not require tests

#### Documentation

- [X] Docs (e.g. `README`s) were updated in this PR
- [ ] A follow-up issue to update official docs has been filed here: [insert issue ID]()
- [ ] This PR does not require updating any documentation

#### Behavior

- [ ] This PR changes product behavior and has been reviewed by a PO, or
- [ ] These changes are part of a larger initiative that will be reviewed later, or
- [X] No behavior was changed with this PR

#### Security

- [ ] Security architect has reviewed the changes in this PR,
- [ ] These changes are part of a larger initiative with a separate security review, or
- [ ] There are no security aspects to these changes

2022-02-25 17:08 UTC, szh reviewed
Looks good. I left a few nits

2022-02-25 17:08 UTC, szh commented on PUSH_TO_FILE.md
> +| `conjur.org/container-mode`         | `CONTAINER_MODE`      | Allowed values: <ul><li>`init`</li><li>`application`</li></ul>Defaults to `init`.<br>Must be set (or default) to `init`for Push to File
Should we put a note about sidecar mode in parentheses so it doesn't appear to contradict the rotation docs?

2022-02-25 17:08 UTC, szh commented on ROTATION.md
> +| No change in secret files, no secret files written |CSPFK018I| This is an info message and not an error, the Secrets Provider did not detect a change in secrets. No files will be written. |
```suggestion
| No change in secret files, no secret files written |CSPFK018I| This is an info message and not an error, the Secrets Provider did not detect a change in secrets for the secrets group. The secret file for this group will not be written. Note: there may be changes in other secret groups and those files will be written. |
```

2022-02-25 17:08 UTC, szh commented on ROTATION.md
> +| Invalid secrets refresh configuration |CSPFK051E| Secrets refresh is enabled either by setting `conjur.org/secrets-refresh-enabled` to true or setting a duration for `conjur.org/secrets-refresh-int
```suggestion
| Invalid secrets refresh configuration |CSPFK051E| Secrets refresh is enabled either by setting `conjur.org/secrets-refresh-enabled` to true or setting a duration for `conjur.org/secrets-refresh-interval` and the mode is not `sidecar`. The mode must be `sidecar`. |
```

2022-02-25 17:08 UTC, szh commented on ROTATION.md
> +Additional enhancements to this feature include
```suggestion
Future enhancements to this feature include
```

2022-02-25 17:28 UTC, rpothier commented on ROTATION.md
> +| No change in secret files, no secret files written |CSPFK018I| This is an info message and not an error, the Secrets Provider did not detect a change in secrets. No files will be written. |
Thanks for the clarification!

2022-02-25 17:36 UTC, szh approved these changes
LGTM! 👍

2022-02-25 21:19 UTC, alexkalish requested changes

2022-02-25 21:19 UTC, alexkalish commented
@rpothier: Doc overall looks great!  My review is mostly cosmetic.  Thanks.

2022-02-25 22:09 UTC, rpothier commented on ROTATION.md
> +| `conjur.org/secrets-refresh-enabled`  |  Defaults to `false` unless `conjur.org/secrets-rotation-interval` is explicitly set. Secrets Provider will exit with error if this is set to `false` and `co
The current behaviour is that if `conjur.org/secrets-refresh-enabled` is not set and `conjur.org/secrets-rotation-interval` has a valid duration then refresh will be enabled. Does this behaviour need to change?

2022-02-28 18:56 UTC, alexkalish commented on ROTATION.md
> +| `conjur.org/secrets-refresh-enabled`  |  Defaults to `false` unless `conjur.org/secrets-rotation-interval` is explicitly set. Secrets Provider will exit with error if this is set to `false` and `co
That behavior is fine.  Mostly, I want the docs to reflect valid values for the annotation.

2022-02-28 19:05 UTC, rpothier commented on ROTATION.md
> +| `conjur.org/secrets-refresh-enabled`  |  Defaults to `false` unless `conjur.org/secrets-rotation-interval` is explicitly set. Secrets Provider will exit with error if this is set to `false` and `co
Go it, thanks. Updated the description.

2022-02-28 20:55 UTC, alexkalish approved these changes

2022-02-28 20:56 UTC, merged